Converting Excel to PDF
Arundhathy-k/TechNotify pull request #14
Opened 2024-12-19 11:11 UTC by Arundhathy-k

Extract the data from Excel sheet and create html design for each row and convert it into pdf. Upload this pdf into S3 bucket.

2025-01-08 18:39 UTC, dhanyesh requested changes

2025-01-08 18:39 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/HtmlGeneratorService.java
> +        data.put("firstName", user.getFirstName());
Try to improve the logic, use some other logic to accommodate the changes

2025-01-08 18:39 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +                futures.add(CompletableFuture.supplyAsync(() -> processRowAndGeneratePdf(row), cpuExecutor));
if possible use parallel stream for processing

2025-01-08 18:39 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +        String fileName = user.getFirstName() + "_" + timestamp + ".pdf";
you are using string for concatenation it's not good idea.

2025-01-08 18:40 UTC, dhanyesh requested changes

2025-01-08 18:40 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +            for (int i = 1; i < sheet.getPhysicalNumberOfRows(); i++) { // Skip header row
Avoid using for loop

2025-01-08 18:42 UTC, dhanyesh requested changes
Write IT and JUnit test for this task

2025-01-09 05:04 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +            for (int i = 1; i < sheet.getPhysicalNumberOfRows(); i++) { // Skip header row
Avoided using for loop.

2025-01-09 05:16 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +        String fileName = user.getFirstName() + "_" + timestamp + ".pdf";
Changed using string for concatenation.

2025-01-09 06:02 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/app/service/HtmlGeneratorService.java
> +        data.put("firstName", user.getFirstName());
Improved the logic.

2025-01-09 06:46 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +                futures.add(CompletableFuture.supplyAsync(() -> processRowAndGeneratePdf(row), cpuExecutor));
Used parallel stream for processing.

2025-01-09 14:18 UTC, dhanyesh requested changes
Why you deleted S3 service and S3 service Test classes

2025-01-09 14:19 UTC, dhanyesh requested changes

2025-01-09 14:19 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
Why you remove this file

2025-01-13 05:57 UTC, dhanyesh requested changes

2025-01-13 05:57 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +                .firstName(getCellValue(row, 0))
can you please improvise this here you are doing 0,1,2,3 so on check any other alternate way

2025-01-13 05:57 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/config/ValidatorConfig.java
> +    public Validator validator() {
What reason you are creating validator bean ?

2025-01-13 09:22 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/config/ValidatorConfig.java
> +    public Validator validator() {
Validator bean removed.

2025-01-15 07:56 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +                .firstName(getCellValue(row, 0))
Improvised the code.

2025-01-15 08:59 UTC, dhanyesh requested changes

2025-01-15 08:59 UTC, dhanyesh commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +             for (ConstraintViolation<User> violation : violations) {
Don't use for loop

2025-01-15 10:27 UTC, Arundhathy-k commented on awsService/src/main/java/com/kovan/app/service/S3Service.java
> +             for (ConstraintViolation<User> violation : violations) {
Changed for loop.

2025-01-16 06:21 UTC, merged