Added Junit and IT test cases.
Arundhathy-k/TechNotify pull request #7
Opened 2024-10-30 12:37 UTC by Arundhathy-k

Added Junit and IT test cases for NewsService module. All test cases are passed, and coverage is more than 90%.

2024-10-30 15:31 UTC, dhanyesh requested changes

2024-10-30 15:31 UTC, dhanyesh commented on mongo-dao/src/main/java/com/kovan/dto/NewsDto.java
> +
why do we need this space

2024-10-30 15:31 UTC, dhanyesh commented on newsService/pom.xml
> +        <dependency>
why do we need this dependency here.(jakson)

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/main/java/com/kovan/app/controller/NewsServiceController.java
> +
remove extra space

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/main/java/com/kovan/app/controller/NewsServiceController.java
> +
remove extra space

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/main/java/com/kovan/app/service/NewsService.java
> +                articles.getFirst().getPublishedAt(),
Good you learned getFirst() method. appreciate it!

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +    @Autowired
Is this really needed ?

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +        cleanup();
check assert after that you have to validate datas are getting flushed or not

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +        System.out.println(newsList.size());
Don't need println I asked you to add sysout only for your testing.

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +
remove extra space

2024-10-30 15:31 UTC, dhanyesh commented on newsService/src/test/java/com/kovan/unit/NewsServiceTests.java
> +
remove extra space

2024-10-30 16:19 UTC, Arundhathy-k commented on mongo-dao/src/main/java/com/kovan/dto/NewsDto.java
> +
Removed the extra space.

2024-10-30 16:26 UTC, Arundhathy-k commented on newsService/src/main/java/com/kovan/app/controller/NewsServiceController.java
> +
Removed the extra space.

2024-10-30 16:30 UTC, Arundhathy-k commented on newsService/src/main/java/com/kovan/app/controller/NewsServiceController.java
> +
Removed extra space.

2024-10-30 16:32 UTC, Arundhathy-k commented on newsService/src/main/java/com/kovan/app/service/NewsService.java
> +                articles.getFirst().getPublishedAt(),
Thanks for the appreciation.

2024-10-30 16:35 UTC, Arundhathy-k commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +        System.out.println(newsList.size());
Removed println.

2024-10-30 16:36 UTC, Arundhathy-k commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +
Removed extra spaces.

2024-10-30 16:38 UTC, Arundhathy-k commented on newsService/src/test/java/com/kovan/unit/NewsServiceTests.java
> +
Removed extra space.

2024-10-30 16:40 UTC, Arundhathy-k commented on newsService/pom.xml
> +        <dependency>
Removed dependency.

2024-10-30 17:42 UTC, Arundhathy-k commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +    @Autowired
Yes. Junit 5 is not supporting constructor injection. So @Autowired annotation is needed.

2024-10-30 17:53 UTC, Arundhathy-k commented on newsService/src/test/java/com/kovan/integration/NewsServiceControllerIT.java
> +        cleanup();
assert added .

2024-10-31 05:09 UTC, dhanyesh requested changes

2024-10-31 05:09 UTC, dhanyesh commented on mongo-dao/src/main/java/com/kovan/dto/NewsDto.java
remove extra space

2024-10-31 05:09 UTC, dhanyesh commented on newsService/pom.xml
> +            <groupId>org.springframework.boot</groupId>
check this dependency is needed or not

2024-10-31 05:09 UTC, dhanyesh commented on mongo-dao/src/main/java/com/kovan/dto/NewsDto.java
>  @Data
where is @Builder annotation?

2024-10-31 05:12 UTC, dhanyesh requested changes
Where is new branch for Junit ticket ?

2024-10-31 05:41 UTC, Arundhathy-k commented on mongo-dao/src/main/java/com/kovan/dto/NewsDto.java
removed extra space.

2024-10-31 05:41 UTC, Arundhathy-k commented on mongo-dao/src/main/java/com/kovan/dto/NewsDto.java
>  @Data
@builder annotation already exists.

2024-10-31 05:52 UTC, Arundhathy-k commented on newsService/pom.xml
> +            <groupId>org.springframework.boot</groupId>
Removed that dependency.

2024-10-31 05:55 UTC, Arundhathy-k commented
Forgot to create new branch. Hence closing this pull request.

2024-10-31 05:56 UTC, Arundhathy-k commented
Forgot to create new branch. Hence closing this pull request.

2024-10-31 05:56 UTC, closed without merging